version: "3.1"
nlu:
- intent: boc_smart_salary_saver_description
  examples: |
    - What is BOC Smart Salary Saver account?
    - Tell me about BOC Smart Salary Saver
- intent: boc_smart_salary_saver_eligibility
  examples: |
    - Who can apply for BOC Smart Salary Saver?
    - What are the eligibility criteria for BOC Smart Salary Saver?
- intent: boc_smart_salary_saver_benefits
  examples: |
    - What benefits does BOC Smart Salary Saver offer?
    - What are the benefits of BOC Smart Salary Saver?
- intent: boc_smartgen_description
  examples: |
    - Explain the features of BOC SmartGen
    - What is BOC SmartGen account?
- intent: boc_smartgen_eligibility
  examples: |
    - Who can apply for BOC SmartGen?
    - What are the eligibility criteria for BOC SmartGen?
- intent: boc_smartgen_benefits
  examples: |
    - Tell me the advantages of BOC SmartGen.
    - What are the benefits of BOC SmartGen?
- intent: check_human
  examples: |
    - are you a robot
    - are you real
    - bot?
    - am i speaking to an ai?
    - are you robot
    - are you a bot?
    - are you ai
    - are you a real bot?
    - are you virtual?
    - are you a rasa bot?
    - are you an ai?
    - are you really a bot
    - are you sure that you're a bot?
    - are you a chatbot
    - are you artificial
    - are you real?
    - are you artificial intelligence
- intent: help
  examples: |
    - What are the things that you can do?
    - what can you do?
    - hello what can you do for me
    - how can you help me
    - help pls
    - can you do anything else?
    - what can you help me with?
    - hep me
    - help me
    - can you help me?
    - help?
    - What else can you help me with?
    - help please
    - what can I ask you?
    - help, what do you do
    - how do I use this
- intent: ask_transfer_charge
  examples: |
    - is there a transfer fee
    - will i be charged for a transaction?
    - is there a charge when I send money to someone
    - do transfers cost something?
    - Will I be charged for transferring money
    - how much is the transfer fee
    - okay but how much to move this money?
    - I sent money to my friend will I be charged extra for that
    - whats the cost of transferring money
    - if I send money to someone will I be charged extra for that?
    - what is the fee for sending money to someone else
    - whats the xfer price for this account
    - how much is the fee to shift my money around
    - are you gonna bill me for this exchange
    - tell me about transfer fees
    - Is there a charge
    - what am I charged upon money transfer
    - are there any transaction fees or charges I should know about?
- intent: check_earnings
  examples: |
    - show me how much I've earned in the last week
    - how much money have I earned?
    - how much money is in the money making machine account?
    - how much did I make
    - how much was deposited in my account in the last two weeks?
    - how much was deposited in January
    - rent is due soon how much do I have in my account
    - how much cash is rolling through my account
    - How much money did I make last week?
    - What did I earn last month?
    - am I a millionaire
    - How much have i earned?
    - How much money did I make last year?
    - check deposits for last week
    - what did I make in the last year?
    - can i afford to go on vacation
    - am I rich yet?
- intent: deny
  examples: |
    - i don't want either of those
    - no
    - i don't want to give you my email
    - no thanks
    - never
    - not really
    - i dont want to
    - I don't think so
    - i'm not sure
    - i guess it means - no
    - Nothing!
    - i don not like this
    - I dunno
    - i'm afraid not
    - i dont want to accept :P lol
    - i don't think so
    - n
    - i decline
- intent: check_recipients
  examples: |
    - Who can I send money to?
    - Show the recipient list
    - whats my recipient list
    - Who is a valid payee
    - tell me who I can share my money with
    - can I see the list of known recipients?
    - Who can I transfer money to?
    - who can I pay?
    - Who all can I transfer money to?
    - Show me my list of recipients
    - if I want to transfer money can i send it to anyone
    - who exactly am I able to send money to
    - Who is on your list?
    - who is in my list of kown recipients?
    - Who are my known recipients
    - who can I transfer money to?
    - who's in my recipient list?
    - Show me people I can send money to
- intent: greet
  examples: |
    - hi there
    - hi
    - hallo
    - good evening
    - hey
    - Hi
    - good morning
    - good day
    - HEY
    - hi!
    - HI
    - hello its ella
    - hey there
    - yo
    - hello
    - Hello
    - Hello?
    - howdy
- intent: out_of_scope
  examples: |
    - Can YouTube talk?
    - Fridge Isn't Running
    - I want to know the weather
    - what is the weather
    - Can you give me your datacenter's password
    - what is the weather today
    - I want a pizza
    - I want to order a pizza
    - my tv isn't working
    - what year is it
    - ofif fsdfafsfs
    - Can you please send me an uber
    - order a pizza
    - Can you make sandwiches?
    - what the weather today ?
    - hows the weather
    - Can you call me back ?
    - Can you give me your datacenter's password?
- intent: human_handoff
  examples: |
    - operator
    - can I speak to an agent
    - chat with a live agent
    - transfer to a human
    - can i talk to human
    - can I talk to human
    - connect me to a real person
    - i want to talk to a real person
    - real human
    - i want to talk to a human
    - can i talk to a real person?
    - let me speak to a real person please
    - I need a real person
    - give me a person please
    - i want human :(
    - I want a human
    - can I talk to human?
    - let me speak to a real person
    - talk to human
    - handoff
- intent: thankyou
  examples: |
    - okay thank you goodbye
    - um okay thank you good bye
    - thanks goodbye
    - I see, thanks
    - Thanks!
    - thank you and good bye
    - thanks!
    - thank you
    - thnks
    - great
    - thank you bye
    - good job bot
    - thanks f
    - it's good :-)
    - thanks for your information
    - thankyou
    - okay thank you
    - thank you goodbye
    - thx
    - thanks you
    - and thats all thank you and good bye
- intent: goodbye
  examples: |
    - GOODBYE
    - good night
    - good bye
    - Thanks a lot. See ya later
    - bye bye bot
    - Adios
    - bye udo
    - ok i gtg
    - i'm done
    - farewell
    - quit
    - goodnight
    - bye
    - bye bye
    - goodbye.
    - ciao
    - BYEE
    - gotta go
    - bye was nice talking to you
    - bye for now
    - cya
    - byee
    - have a good day. time to go, bye
- intent: search_transactions
  examples: |
    - How much did I spend last month?
    - What did I spend at [Legoland](vendor_name) last month?
    - What did I spend at [Legoland](vendor_name) last year?
    - I want to search my transactions with [amazon](vendor_name)
    - I want to search my past transactions
    - How much did I spend at Burger King last month?
    - i want to see my transaction history
    - i want to check my spending history
    - I want to check my spending
    - I need to check my spending history
    - how much did I spend at [Target](vendor_name) this week?
    - what is my typical spending at [Amazon](vendor_name)?
    - How much money did I lose to [starbucks](vendor_name) in may?
    - What did I spend at [Costco](vendor_name) last month?
    - what places have I spent money?
    - where did I spend the most money last month?
    - Can you tell me how much I spent at [Ikea](vendor_name) this month?
    - what did I spend at [target](vendor_name) last month
    - Can you tell me how much I spent on coffee this month?
    - can i seem my transactions with [target](vendor_name)
    - how much did i spend at [starbucks](vendor_name) last month?
    - Can you tell me how much I spent at coffeeshops this month?
    - can I search my transaction history
    - I want to check my spending history at [starbucks](vendor_name)
    - Oh how much did I actually spend at [target](vendor_name) last month? I'd love to know.
    - I want to check my spending history
- intent: affirm
  examples: |
    - Yes, I accept
    - sweet
    - yess please
    - yeah
    - Yeah sure
    - Yep!
    - Ok
    - YES
    - ye
    - That would be great
    - y
    - Yea
    - Yes I do
    - cool,
    - yes plz
    - correct
    - Yes please
    - of course
    - Yepp
    - Yes please!
    - Yep
    - yes
    - okay
    - YUP
    - yup
    - yes...
    - Sure
- intent: pay_cc
  examples: |
    - pay 100 towards [emblem](credit_card) [card](account_type), tomorrow
    - Pay my [discover](credit_card)
    - I would like to pay the [minimum balance](amount-of-money) on my [embelm](credit_card) [card](account_type)
    - i want to pay off my [emblem](credit_card) [credit card](account_type)
    - I want to pay my [justice bank](credit_card) bill
    - could I pay off my [credit card]{"entity": "account_type", "value": "credit"}?
    - I want to pay my [current balance](amount-of-money) on my [emblem](credit_card) [credit card](account_type) today
    - I want to pay my [iron bank](credit_card) bill
    - I want to pay 100 dollars toward my [Emblem](credit_card) [card](account_type), tomorrow
    - Pay my [visa](credit_card)
    - I want to pay the [current balance](amount-of-money) on my [credit card](account_type)
    - pay off my [credit card]{"entity": "account_type", "value": "credit"}
    - i want to pay my [credit card](account_type)
    - i need to pay off my [emblm](credit_card) [credit card](account_type)
    - I want to pay my [MasterCard](credit_card) bill
    - Can I schedule a payment towards my [credit card](account_type) for tomorrow?
    - can I pay my [card]{"entity": "account_type", "value": "credit"}?
    - Let's pay that [credit card]{"entity": "account_type", "value": "credit"} bill
    - id like to pay my bill
    - i would like to pay $1200 to my [credit card]{"entity": "account_type", "value": "credit"}
    - i want to pay off my [credit card](account_type)
    - I want to pay $500 on my [emblem](credit_card) [credit card](account_type) on Sunday
    - I want to pay my [visa](credit_card) bill
    - I want to pay my [credit card](account_type)
    - I want to pay my [credit card](account_type) bill
    - i wanna pay my [credit card]{"entity": "account_type", "value": "credit"}
    - I want to pay my [current balance](amount-of-money) on my [embelm](credit_card) [credit card](account_type)
    - Pay my [card](account_type)
    - can you help me pay the [current balance](amount-of-money) on my [credit card](account_type)
    - i want to pay my [current balance](amount-of-money) on my [emblem](credit_card) [credit card](account_type)
    - I want to pay my [card](account_type)
- intent: transfer_money
  examples: |
    - transfer money to [sara](PERSON)
    - transfer money
    - I need to transfer money to [Jeff](PERSON), my son
    - I need to transfer money to my grandma [Judith](PERSON).
    - can I transfer money to [Kyle Gardner](PERSON)?
    - Pay [Karen](PERSON) 60 Euros
    - pay [Evan Oslo](PERSON)
    - i want to transfer $100 to my [daughter](PERSON)
    - pay [Lisa](PERSON) please
    - I need to transfer money to my co-worker who paid for lunch
    - Hi I like to send money
    - I would like to transfer 50$ to [Joschka](PERSON)
    - i want to transfer money to [Latisha](PERSON)
    - transfer $60 to [Jason Jacob](PERSON)
    - send $50 to [john jacob](PERSON)
    - I want to transfer $100 to [Bob](PERSON)
    - II want to transfer to [Kelly](PERSON)
    - I want to pay [John](PERSON)
    - i want to transfer $400 to [Akela](PERSON)
    - can I transfer money to my [mom](PERSON)
    - I want to pay [Bert](PERSON)
    - transfer $60 to [Sally](PERSON)
    - I want to pay [Paula Handy](PERSON)
    - Please transfer 50 dollars to [Andreas](PERSON)
    - Hi I like to send money to [John](PERSON)
    - Pay $50 to [Pat](PERSON)
    - I need to send money to my kid
    - Ok pay [Emma](PERSON)
    - need to transfer money
    - I need to transfer money to a friend
    - Pay [Percy](PERSON) $50
    - can I pay someone
    - pay my friend
    - Can I transfer money to a friend?
    - pay [Mona](PERSON) $60
    - I need to make an urgent transfer to [Bob](PERSON), can you do it?
    - i want to transfer $100 to [Jane smith](PERSON)
    - I'd like to send 50$ to [John](PERSON)
    - I want to pay someone
    - i want to transfer money please
    - can i transfer money to [Sally](PERSON)
- intent: check_balance
  examples: |
    - What's my [credit card](account_type) [balance](amount-of-money)
    - What's my [credit](account_type) account
    - What's my [balance](amount-of-money)?
    - Yeah, I know 😀 Since it's so nice: How much money do I have?
    - check my [credit card]{"entity": "account_type", "value": "credit"} [balance](amount-of-money)
    - How much money is on my [bank](account_type) account?
    - what's my [bank](account_type) account [balance](amount-of-money)
    - what's my [credit card](account_type) account [balance](amount-of-money)?
    - Hello, I would like to know how much money is in much money is in my account
    - what's my [bank](account_type) account [balance](amount-of-money)?
    - check my [credit card]{"entity": "account_type", "value": "credit"} [balance](amount-of-money) [first](account_type)
    - what's my [current balance](amount-of-money)?
    - What's my [emblem](credit_card) [card](account_type) [balance](amount-of-money)
    - What's the [balance](amount-of-money) on that account?
    - what is my account [balance](amount-of-money)
    - whats my [emblm](credit_card) [card](account_type) [balance](amount-of-money)?
    - Hi, I need to know how much money is in my [checking](account_type) account
    - How much money is on my account?
    - What is my [emblem](credit_card) [balance](amount-of-money)?
    - so.... what's my [balance](amount-of-money)?
    - What's my [justice bank](credit_card) [balance](amount-of-money)
    - whats my [credit card](account_type) [balance](amount-of-money)
    - Show me my [iron bank](credit_card) [balance](amount-of-money)
    - whats my [bank](account_type) account [balance](amount-of-money)
    - what's my [emblm](credit_card) [credit card](account_type) [balance](amount-of-money)?
    - How much do I have on that account?
    - Whats the [balance](amount-of-money) on my [credit](account_type) account
    - what is my [bank](account_type) account [balance](amount-of-money)
    - How much money have i spent lately>
    - How much money do I owe on my [credit cards](account_type)
    - Wait, I'll have to check my balance first. Can you do that please?
    - what places have I spent money?
    - How much money do I have?
    - hi, whats my account bal please
    - What's left on that account?
    - whats my [current balance](amount-of-money)
    - Show me my [credit](account_type) accounts
    - Can you tell me my account [balance](amount-of-money)?
    - Yeah, I like coffee 👀 But how much money do I have?
    - whats my account [balance](amount-of-money)
    - Balance please
    - what's my [balance](amount-of-money)?
    - Show me my [credit card](account_type) [balance](amount-of-money)
- intent: inform
  examples: |
    - [gary](PERSON)
    - 5000
    - My [visa](credit_card)
    - the past two days
    - my [minimum balance](amount-of-money)
    - [starbucks](vendor_name)
    - all of them
    - the [full balance](amount-of-money)
    - Lisa Macintyre
    - [John](PERSON)
    - percy donald
    - my [credit card]{"entity": "account_type", "value": "credit"} account ending in 4321
    - at [target](vendor_name)
    - [emblem](credit_card) account
    - Sara
    - [Target](vendor_name)
    - the [minimum balance](amount-of-money)
    - [visa](credit_card)
    - $500
    - my [current balance](amount-of-money)
    - [current balance](amount-of-money)
    - the [current balance](amount-of-money)
    - [iron bank](credit_card) account
    - today
    - 500
    - [iron bank](credit_card) [credit card](account_type)
    - towards my [iron bank](credit_card) [card](account_type)
    - [Starbucks](vendor_name)
    - a hundred dollars
    - to my [sister](PERSON)
    - [emblem](credit_card) [credit card](account_type)
    - [Alexandra](PERSON)?
    - [emblem](credit_card)
    - [bill](PERSON)
    - for friday
    - for sunday
    - [iron bank](credit_card)
    - I want to pay the [current balance](amount-of-money)
    - Evan Oslo
    - for tomorrow
    - Please schedule it for the first of next month
    - the last two weeks
    - htthis weekend
    - danIelle smilanich
    - A friend.
    - [justice bank](credit_card) account
    - Jane
    - [mastercard](credit_card)
    - William Baker
    - [emblem](credit_card) [card](account_type)
    - my [emblem](credit_card) [credit card](account_type)
    - the past month
    - [Bob](PERSON)
    - 100 dollars
    - Melinda
    - Karen Lancaster
    - [justice bank](credit_card)
    - today please
    - My [Visa](credit_card) account
    - last week
    - my [emblem](credit_card) [card](account_type)
    - [Iron Bank](credit_card)
    - [anusha](PERSON)
    - at [starbucks](vendor_name)
    - [full](amount-of-money)
    - [cheng](PERSON)
    - Katy Parrow
    - My chase
    - $10
    - Kyle Gardner
    - [minimum balance](amount-of-money)
    - yesterday
    - [darnell](PERSON)
    - my [iron bank](credit_card) [credit card](account_type)
    - I want to pay the [minimum balance](amount-of-money) on my [emblem](credit_card) [credit card](account_type) today
    - [Claire](PERSON)
    - my [rasa](credit_card) account
    - $100
    - my [justice bank](credit_card) [credit card](account_type)
    - 1000 dollars
    - Percy
    - Laura Schilling
    - In that case, let's go with Percy
    - my [justice bank](credit_card) [card](account_type)
    - to my [brother](PERSON)
    - my [dad](PERSON)
    - tomorrow
    - my wife's
    - [target](vendor_name)
- synonym: credit
  examples: |
    - credit card
    - card
    - credit cards
    - credit account
    - credit accounts
    - cards
    - credit card account
- synonym: emblem
  examples: |
    - emblm
    - embelm
    - Emblem
- synonym: current balance
  examples: |
    - balance
    - full
    - full balance
