name: Rasa CI/CD Pipeline

on:
  push:
    branches:
      - deploy  # or whatever your primary branch is
jobs:
  training-testing-english:
    name: Training and Testing English
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Rasa Train and Test for English    
      uses: RasaHQ/rasa-train-test-gha@main
      with:
        rasa_version: '3.5.15-full'
        workspace: ./src/English
        model: ./models
        data_validate: true
        # rasa_train: true
        # cross_validation: true
        rasa_test: true
        test_type: all
        publish_summary: true
        github_token: ${{ secrets.GITHUB_TOKEN }}
  training-testing-tamil:
    name: Training and Testing Tamil
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Rasa Train and Test for Tamil
      uses: RasaHQ/rasa-train-test-gha@main
      with:
        rasa_version: '3.5.15-full'
        workspace: ./src/Tamil
        model: ./models
        data_validate: true
        # rasa_train: true
        # cross_validation: true
        rasa_test: true
        test_type: all
        publish_summary: true
        github_token: ${{ secrets.GITHUB_TOKEN }}
  deploy_english:
    name: Deploy English
    needs: training-testing-english
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build the Docker image
      run: cd ./src/English && docker build . --file Dockerfile -t anoshan265/rasa-chatbot 
    - name: Push the Docker image
      run: cd ./src/English && docker push anoshan265/rasa-chatbot
    - name: Login to Okteto and deploy
      if: ${{ github.event_name == 'push' }}
      run: |
        cd ./src/English
        curl https://get.okteto.com -sSfL | sh
        okteto login --token ${{ secrets.OKTETO_TOKEN }}
        okteto deploy --build -f .\docker-compose.yml
  deploy_tamil:
    name: Deploy Tamil
    needs: training-testing-tamil
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build the Docker image
      run: cd ./src/Tamil && docker build . --file Dockerfile -t anoshan265/rasa-chatbot-ta
    - name: Push the Docker image
      run: cd ./src/Tamil && docker push anoshan265/rasa-chatbot-ta
    - name: Login to Okteto and deploy
      if: ${{ github.event_name == 'push' }}
      run: |
        cd ./src/Tamil
        curl https://get.okteto.com -sSfL | sh
        okteto login --token ${{ secrets.OKTETO_TOKEN }}
        okteto deploy --build -f .\docker-compose.yml